### ISSUE TITLE
Make sure conversion to CSV working

### ISSUE THREAD

**Issue by ghost** [Open-Telecoms-Data/cove-ofds#3]

**Comment by duncandewhurst** [comment]
I've updated the issue title, since we are not offering spreadsheet conversion.

It looks like some of the options specified in https://github.com/Open-Telecoms-Data/lib-cove-ofds/issues/10#issuecomment-1290201200 are not set, at least `--truncation-length=9` and `--main-sheet-name=networks`:

![image](https://user-images.githubusercontent.com/19265814/200444061-31b76be0-888f-43fa-af83-10edcebd9a65.png)

Once set, we can check that the files generated by uploading `examples/network-package.csv` are identical to those in `examples/csv`.

**Comment by ghost** [comment]
main-sheet-name was set but it wasn't schema aware - branch 2022-11-08 now has schema and truncation-length set

**Comment by duncandewhurst** [comment]
I'm still seeing the main sheet named 'main' rather than 'networks':

![image](https://user-images.githubusercontent.com/19265814/200691138-10d649a1-68af-486f-b25d-e6cd3350ad67.png)

**Comment by ghost** [comment]
ready to test on live

**Comment by lgs85** [comment]
For me, this has worked with the csv files and they all look identical to the example data, but if I download the zipped folder I still get `main.csv`

**Comment by odscjames** [comment]
I see it as main.csv - where are you seeing this? Can you make sure you have uploaded new data and you aren't looking at data you have previously uploaded?

**Comment by duncandewhurst** [comment]
That's weird, when I upload `examples/network-package.json`, I get a zip file containing `networks.csv`:

![image](https://user-images.githubusercontent.com/19265814/204903772-15a64249-31d5-456e-8b93-ad7fb7ea6e7d.png)

What data did you upload?

**Comment by lgs85** [comment]
Now working for me, I think I was using an old file, sorry and thanks both!
