### ISSUE TITLE
GeoJSON upload not working?

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/cove-ofds#60]
I'm currently getting an error on the live version with the GeoJSON [example files](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/tree/0.1/examples/geojson) `nodes.geojson` and `spans.geojson`, saying that they are not recognised as GeoJSON.

<img width="354" alt="image" src="https://user-images.githubusercontent.com/10154525/203830836-055faa63-2c25-4d6d-a817-9bb44975b336.png">

Any ideas what's up? Sorry if it's me doing something silly.

**Comment by duncandewhurst** [comment]
That's odd - it's working OK for me: https://ofds.cove.opendataservices.coop/data/7443d644-86e8-40a4-b2a7-9c0d18138931.

If you right clicked and saved the files in the link that you shared, you will have ended up with the HTML pages. You need to open the individual files in the GitHub and then use the 'Raw' button to get the JSON file.

If that's the case, perhaps we should consider improving the feedback to users, i.e. something along the lines of "The file you uploaded has the .geojson extension but it's MIMETYPE is..."

I think this issue it probably belongs in cove-ofds since that's where the settings for accepted content types and extensions are, which appear to be configured correctly for `.geojson` files: https://github.com/Open-Telecoms-Data/cove-ofds/blob/222af62f9135d895bb34ad783240c38b043e9285/cove_project/settings.py#L172-L175

**Comment by lgs85** [comment]
>If you right clicked and saved the files in the link that you shared, you will have ended up with the HTML pages. You need to open the individual files in the GitHub and then use the 'Raw' button to get the JSON file.

Thankfully I didn't do anything this daft. For me at least, on the live version, this appears to be about the file extension. Renaming the files to `nodes.geo.json` and `spans.geo.json` fixes the issue. I'll let others decide whether this should be moved to cove-ofds

**Comment by ghost** [comment]
> Renaming the files to nodes.geo.json and spans.geo.json fixes the issue.

That is odd - as @duncandewhurst points out ".geojson" is already allowed. When I tried locally it worked. I'm a bit stuck.

**Comment by duncandewhurst** [comment]
Hmm, I checked again on live and its working for me with the examples linked in the issue description: https://ofds.cove.opendataservices.coop/data/780242dd-957a-4c80-a5c0-4202b579f9d6 

@lgs85 please could you:

* Check that you can reproduce the problem
* Share the URL you're using
* Attach exactly the files that you are trying to upload to this issue

**Comment by lgs85** [comment]
>- Check that you can reproduce the problem

Yes, also checked it's not a browser issue and occurs on chrome, safari and firefox

>- Share the URL you're using

https://ofds.cove.opendataservices.coop/

>- Attach exactly the files that you are trying to upload to this issue

[This nodes file](https://raw.githubusercontent.com/Open-Telecoms-Data/open-fibre-data-standard/0.1-dev/examples/geojson/nodes.geojson)
[This spans file](https://raw.githubusercontent.com/Open-Telecoms-Data/open-fibre-data-standard/0.1-dev/examples/geojson/spans.geojson)

Again, they work if I rename the files to have a `.json` extension. With a `.geojson` extension I get redirected to [this url](https://ofds.cove.opendataservices.coop/new_geojson), with the error screenshotted in the original post.

Apologies if this is something at my end.

**Comment by lgs85** [comment]
After talking through with @odscjames it turns out that this is because my OS is sending the `.geojson` files as `application/octet-stream` attachments. We can add this to `ALLOWED_GEOJSON_CONTENT_TYPES`.

**Comment by duncandewhurst** [comment]
Closed since the related PR is closed.
